site_name: Python Course
site_author: Andrea Diamantini

copyright: >
  Andrea Diamantini (c) 2022-inf<br>
  <a href="#__consent">Change Cookie Settings</a><br>
  This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>

# -----------------------------------------------------------------------------
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font: False
  language: it
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  plugins:
    - search:
        lang: it

extra:
  consent:
    title: Consenso all'uso dei Cookie(s)
    description: >
      Questo sito memorizza sul tuo PC solo due cookies: uno per ricordarsi se hai già visto questo avviso,
      un altro per ricordarsi il tema di visualizzazione (chiaro/scuro).<br>
      Se non acconsenti, dovrai selezionare ogni volta la tua scelta.<br>
      In fondo alla pagina c'è il link per fare reset ;)
    actions:
      - accept
      - reject

extra_css:
  - stylesheets/extra.css

# -----------------------------------------------------------------------------------------------

markdown_extensions:
  - admonition: {}
  - attr_list: {}
  - toc: {}
  - def_list: {}
  - pymdownx.emoji: {}
  - pymdownx.tasklist: { custom_checkbox: True }
  - pymdownx.highlight: { anchor_linenums: True }
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences: {}
  - pymdownx.keys: {}

  # -----------------------------------------------------------------------------------------------

nav:
  - Home: index.md
  # ---------------------------------------------------------------
  - Basics:
      - Introduzione: basics/000_first.md
      - Installazione: basics/001_install.md
      - Prime cose: basics/100_basics.md
      - Variabili e Operatori: basics/101_var.md
      - Alternanza: basics/102_alt.md
      - Ripetizione: basics/103_iter.md
      - Sequenze: basics/104_seq.md
      - Funzioni: basics/105_funz.md
      - Moduli: basics/106_mod.md
      - Python Standard Library: basics/106_psl.md
      - PyPi: basics/106_pypi.md
      - Files: basics/107_files.md
      - CSV: basics/108_csv.md
  # ---------------------------------------------------------------
  - OOP:
      - Introduzione: OOP/000_intro.md
      - Classi e Oggetti: OOP/001_classes_objects.md
      - Ereditarietà: OOP/002_inheritance.md
      - Caratteristiche Avanzate: OOP/003_advanced.md
    # ---------------------------------------------------------------
  - wxPython:
      - Introduzione: wx/000_intro.md
      - Primi concetti: wx/101_first_things.md
      - Eventi: wx/102_events.md
      - Widgets: wx/110_widgets.md
      - Layout: wx/120_layout.md
      - Esercizi Completi: wx/130_full_ex.md
      - Dialogs: wx/140_dialogs.md
      - Immagini: wx/150_images.md
      - Timer(s): wx/160_timer.md
      - Full GUI: wx/170_full_gui.md
      - Widgets Avanzate: wx/171_advanced.md
      - Printing: wx/172_printing.md
      - Network: wx/180_network.md
      - wx Tools: wx/299_tools.md
    # ---------------------------------------------------------------
  - Insights:
      - Introduzione: insights/00_intro.md
      - uv: insights/01_uv.md
      - Turtle: insights/11_turtle.md
      - PyGame: insights/12_pygame.md
      - MySql: insights/41_mysql.md
      - Arduino: insights/51_arduino.md
      - Numeri reali: insights/91_reals.md
      - Interi, bytes, stringhe: insights/92_ibs.md
      - asyncio: insights/99_asyncio.md
